name: "Build and push Windows images"
description: "Builds wcow images with MSVC and CUDA"

inputs:
  image:
    type: string
    required: true
    description: Image to test

runs:
  using: composite
  steps:

    - name: "Push ${{ inputs.image }}"
      id: push
      shell: powershell
      run: |
        docker push ${{ inputs.image }}
