name: "Build Windows images"
description: "Builds wcow images with MSVC and CUDA"

inputs:
  repo:
    type: string
    required: true
    description: Image repository
  os:
    type: string
    required: true
    description: Windows edition
  vs_version:
    type: string
    required: true
    description: MSVC version

outputs:
  image:
    description: URL of tagged and pushed image
    value: ${{ steps.build.outputs.image }}

runs:
  using: composite
  steps:
    - name: "Build ${{ inputs.repo }}:${{ inputs.service }}"
      id: build
      shell: powershell
      env:
        REPO: "${{ inputs.repo }}"
        SERVICE: "${{ inputs.os }}-${{ inputs.vs_version }}"
        TAG: "${{ inputs.repo }}:${{ inputs.os }}-cuda-msvc-${{ inputs.vs_version }}"
      run: |
        images/docker-build.ps1 -msvcVersion ${{ inputs.vs_version }} -edition ${{ inputs.os }}
        echo "image=$ENV:TAG" >> $ENV:GITHUB_OUTPUT
