name: "Test Windows images"
description: "Tests MSVC and CUDA on each container"

inputs:
  image:
    type: string
    required: true
    description: Image to test
  vs_ver:
    type: string
    required: true
    description: Version of VS to test

runs:
  using: composite
  steps:
    - name: "Test ${{ inputs.image }}"
      id: image_test
      shell: powershell
      run: |
        $(pwd)\.github\actions\test-windows-image\action.ps1 -image ${{ inputs.image }} -vs ${{ inputs.vs_ver }}
