# These services are constructed after those in docker-compose.yml

services:
  windows-extend-2022:
    image: "$REPO:${WIN_IMAGE}-cuda-msvc-2022-$MSVC_COMPILER_VER"
    build:
      context: ./windows
      dockerfile: ../msvc.Dockerfile
      args:
        MSVC_COMPILER_VER: "$MSVC_COMPILER_VER"
        MSVC_VER: 17
        ROOT_IMAGE: "$REPO:${WIN_IMAGE}-cuda-msvc-2022"

  windows-extend-2019:
    image: "$REPO:${WIN_IMAGE}-cuda-msvc-2019-$MSVC_COMPILER_VER"
    build:
      context: ./windows
      dockerfile: ../msvc.Dockerfile
      args:
        MSVC_COMPILER_VER: "$MSVC_COMPILER_VER"
        MSVC_VER: 16
        ROOT_IMAGE: "$REPO:${WIN_IMAGE}-cuda-msvc-2019"

  windows-extend-2017:
    image: "$REPO:${WIN_IMAGE}-cuda-msvc-2017-$MSVC_COMPILER_VER"
    build:
      context: ./windows
      dockerfile: ../msvc.Dockerfile
      args:
        MSVC_COMPILER_VER: "$MSVC_COMPILER_VER"
        MSVC_VER: 15
        ROOT_IMAGE: "$REPO:${WIN_IMAGE}-cuda-msvc-2017"
