# These services are constructed after those in docker-compose.yml

services:
  windows-2022-latest:
    image: "$REPO:windows-cuda-msvc-2022-latest"
    build: &windows-build
      context: ./windows
      dockerfile: ../msvc.Dockerfile
      args: &windows-args
        MSVC_COMPILER_VER: "latest"
        MSVC_VER: "17"
        ROOT_IMAGE: "$REPO:windows-cuda-msvc-2022"

  windows-2022-14.36:
    image: "$REPO:windows-cuda-msvc-2022-14.36"
    build:
      <<: *windows-build
      args:
        <<: *windows-args
        MSVC_COMPILER_VER: "14.36"

  windows-2022-14.35:
    image: "$REPO:windows-cuda-msvc-2022-14.35"
    build:
      <<: *windows-build
      args:
        <<: *windows-args
        MSVC_COMPILER_VER: "14.35"

  windows-2022-14.34:
    image: "$REPO:windows-cuda-msvc-2022-14.34"
    build:
      <<: *windows-build
      args:
        <<: *windows-args
        MSVC_COMPILER_VER: "14.34"
