name: "Build and push Windows images"
description: "Builds wcow images with MSVC and CUDA"

inputs:
  repo:
    type: string
    required: true
    description: Image repository
  os:
    type: string
    required: true
    description: Windows edition
  vs_version:
    type: string
    required: true
    description: MSVC version

outputs:
  image:
    description: URL of tagged and pushed image
    value: ${{ steps.push.outputs.image }}

runs:
  using: composite
  steps:

    - name: "Build ${{ inputs.repo }}:${{ inputs.service }}"
      id: build
      shell: powershell
      env:
        REPO: "${{ inputs.repo }}"
        SERVICE: "${{ inputs.os }}-${{ inputs.vs_version }}"
      run: docker compose -f ./images/dockercompose.yml build $ENV:SERVICE --progress=plain

    - name: "Push ${{ inputs.repo }}:${{ inputs.service }}"
      id: push
      shell: powershell
      env:
        TAG: "${{ inputs.repo }}:${{ inputs.os }}-cuda-msvc-${{ inputs.vs_version }}"
      run: |
        echo "image=$ENV:TAG" >> $ENV:GITHUB_OUTPUT
        docker push $ENV:TAG
