name: "Build and push Windows images"
description: "Builds wcow images with MSVC and CUDA"

inputs:
  repo:
    type: string
    required: true
    description: Image repository
  os:
    type: string
    required: true
    description: Windows edition
  vs_version:
    type: string
    required: true
    description: MSVC version

outputs:
  repo:
    value: ${{ steps.build.outputs.repo }}

runs:
  using: composite
  steps:

    - run: docker compose -f ./images/dockercompose.yml build $ENV:SERVICE --progress=plain
      shell: powershell
      env:
        REPO: "${{ inputs.repo }}"
        SERVICE: "${{ inputs.os }}-${{ inputs.vs_version }}"
      id: build
      name: "Build ${{ inputs.repo }}:${{ inputs.service }}"

    - run: docker push $ENV:TAG --progress=plain
      shell: powershell
      env:
        TAG: "${{ inputs.repo }}:${{ inputs.os }}-cuda-msvc-${{ inputs.version }}"
      id: push
      name: "Push ${{ inputs.repo }}:${{ inputs.service }}"
