name: Build Windows Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Test wcow
        run: |
          docker --version
          docker run mcr.microsoft.com/windows/servercore:ltsc2022 "echo hello world"
