name: Build Windows Images

on:
  push:
    paths: [.github/**, images/**]
    branches: [ "main" ]
  pull_request:
    paths: [.github/**, images/**]
    branches: [ "main" ]

  workflow_dispatch:


jobs:
  build-windows-server:
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        edition: [windows-server]
        version: [2017, 2019, 2022]

    name: Build Windows Server images
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: "Build image: ${{ matrix.edition }} + VS${{ matrix.version }}"
        id: build_image
        uses: ./.github/actions/build-windows-image
        with:
          repo: ghcr.io/${{ github.repository }}
          os: ${{ matrix.edition }}
          vs_version: "${{ matrix.version }}"

      - name: "Test image: ${{ steps.build_image.outputs.image }}"
        id: test_image
        uses: ./.github/actions/test-windows-image
        with:
          image: "${{ steps.build_image.outputs.image }}"

      - name: "Push image: ${{ steps.build_image.outputs.image }}"
        id: push_image
        uses: ./.github/actions/push-windows-image
        with:
          image: "${{ steps.build_image.outputs.image }}"

  build-windows-client:
    # Only Windows 2019 supports building Windows 10 images in hyper-v
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        edition: [windows]
        version: [2017, 2019, 2022]

    name: Build Windows client images
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: "Build image: ${{ matrix.edition }} + VS${{ matrix.version }}"
        id: build_image
        uses: ./.github/actions/build-windows-image
        with:
          repo: ghcr.io/${{ github.repository }}
          os: ${{ matrix.edition }}
          vs_version: "${{ matrix.version }}"

      - name: "Test image: ${{ steps.build_image.outputs.image }}"
        id: test_image
        uses: ./.github/actions/test-windows-image
        with:
          image: "${{ steps.build_image.outputs.image }}"

      - name: "Push image: ${{ steps.build_image.outputs.image }}"
        id: push_image
        uses: ./.github/actions/push-windows-image
        with:
          image: "${{ steps.build_image.outputs.image }}"
