name: Build Windows Images

on:
  push:
    paths: [.github/**, images/**]
    branches: [ "main" ]
  pull_request:
    paths: [.github/**, images/**]
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  dispatch-builder-job:
    name: Build Windows Image
    strategy:
      fail-fast: false
      matrix:
        runner: [windows-2019, windows-2022]
        cuda_version: ["12.1", "11.1"]
        isolation: [process, hyperv]
        edition: [windows-server, windows-10]
        vs_version: ["2017", "2019", "2022"]
        exclude:
          # https://learn.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility
          # Exclude Incompatible windows builds
          - runner: windows-2019
            edition: windows-server
          - runner: windows-2022
            edition: windows-10
          # No configuration of windows 10 supports process isolation
          - edition: windows-10
            isolation: process
          # Exclude MSVC 2022 and 11.1 as it is unsupported
          - vs_version: "2022"
            cuda_version: "11.1"
    uses: ./.github/workflows/windows_build.yml
    with:
      runner: ${{ matrix.runner }}
      win_edition: ${{ matrix.edition }}
      vs_version: ${{ matrix.vs_version }}
      cuda_version: ${{ matrix.cuda_version }}
      isolation: ${{ matrix.isolation }}
